
import React, { useRef, useState } from 'react';
import { UserProgress } from '../types';
import { Trophy, Quote, Download, Loader2, Check } from 'lucide-react';
import { Heatmap } from './Heatmap';

// Declare html2canvas on window
declare global {
  interface Window {
    html2canvas: any;
  }
}

interface LongShareProps {
  progress: UserProgress;
}

export const LongShare: React.FC<LongShareProps> = ({ progress }) => {
  const ref = useRef<HTMLDivElement>(null);
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = async () => {
    if (!ref.current || !window.html2canvas) return;
    setGenerating(true);
    
    try {
        const canvas = await window.html2canvas(ref.current, {
            backgroundColor: '#09090b',
            scale: 2, // Retina quality
            useCORS: true // For images
        });
        
        const link = document.createElement('a');
        link.download = `Project${progress.totalDays}_Report_Day${progress.currentDay}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
        
        setDone(true);
        setTimeout(() => setDone(false), 3000);
    } catch (e) {
        console.error("Screenshot failed", e);
        alert("Could not generate image. Please screenshot manually.");
    } finally {
        setGenerating(false);
    }
  };

  const completionRate = Math.round(
    (Object.values(progress.history).reduce((acc, day) => acc + day.completedHabits.length, 0) / 
    (progress.currentDay * progress.customHabits.length)) * 100
  ) || 0;

  return (
    <div className="flex flex-col items-center h-full">
       <div className="flex-1 overflow-y-auto custom-scrollbar w-full flex justify-center p-4">
          {/* The Capture Target */}
          <div 
            ref={ref}
            className="w-full max-w-sm bg-zinc-950 border border-zinc-800 p-8 text-center space-y-8 relative overflow-hidden"
            style={{ minHeight: '800px' }} // Force long height
          >
             {/* Header */}
             <div className="flex flex-col items-center gap-3">
                <div className="w-16 h-16 bg-emerald-500 rounded-2xl flex items-center justify-center shadow-xl shadow-emerald-500/20">
                   <Trophy className="text-black w-8 h-8" strokeWidth={3} />
                </div>
                <div>
                   <h1 className="text-3xl font-black text-white tracking-tighter uppercase">Project {progress.totalDays}</h1>
                   <p className="text-zinc-500 text-sm font-mono uppercase tracking-widest mt-1">Progress Report</p>
                </div>
             </div>

             {/* User Info */}
             <div className="border-t border-b border-zinc-900 py-6">
                <h2 className="text-xl font-bold text-white">{progress.userName || "Challenger"}</h2>
                <p className="text-emerald-500 font-mono text-sm">Day {progress.currentDay} / {progress.totalDays}</p>
             </div>

             {/* Manifesto */}
             {progress.manifesto && (
               <div className="relative px-4">
                  <Quote className="absolute top-0 left-0 text-zinc-800 w-8 h-8" />
                  <p className="text-zinc-300 font-serif italic text-lg leading-relaxed relative z-10">
                    "{progress.manifesto}"
                  </p>
               </div>
             )}

             {/* Stats Grid */}
             <div className="grid grid-cols-2 gap-4">
                <div className="bg-zinc-900 p-4 rounded-xl border border-zinc-800">
                   <p className="text-[10px] text-zinc-500 uppercase tracking-widest font-bold">Level</p>
                   <p className="text-2xl font-bold text-white">{progress.level}</p>
                </div>
                <div className="bg-zinc-900 p-4 rounded-xl border border-zinc-800">
                   <p className="text-[10px] text-zinc-500 uppercase tracking-widest font-bold">Rate</p>
                   <p className="text-2xl font-bold text-emerald-400">{completionRate}%</p>
                </div>
             </div>

             {/* The Heatmap */}
             <div className="py-2">
                <Heatmap progress={progress} />
             </div>

             {/* Footer */}
             <div className="pt-8 pb-4">
                <p className="text-[10px] text-zinc-600 uppercase tracking-[0.3em]">Discipline is Destiny</p>
                <p className="text-[8px] text-zinc-800 mt-2">Generated by Project 50 Tracker</p>
             </div>
          </div>
       </div>

       {/* Actions */}
       <div className="p-4 w-full bg-zinc-900 border-t border-zinc-800 flex justify-center">
          <button 
            onClick={handleDownload}
            disabled={generating}
            className="flex items-center gap-2 px-6 py-3 bg-white text-black rounded-full font-bold text-sm hover:bg-zinc-200 transition-colors shadow-lg disabled:opacity-50"
          >
            {generating ? <Loader2 className="animate-spin" size={16} /> : done ? <Check size={16} /> : <Download size={16} />}
            {generating ? "Generating..." : done ? "Saved!" : "Download Report"}
          </button>
       </div>
    </div>
  );
};
